---
name: "Ignore"
guid: "bd08ce53-8040-4043-a96a-55933807d7d8"
version: "1.0.0.0"
targetAbi: "10.8.0.0"
framework: "net6.0"
overview: "Super simple plugin to ignore files based on `.jellyfinignore`."
description: >
  Super simple plugin to ignore files based on `.jellyfinignore`.
category: "General"
owner: "arition"
artifacts:
- "Jellyfin.Plugin.Ignore.dll"
- "Ignore.dll"
changelog: >
  2022-08-22 Init
