---
name: "Ignore"
guid: "bd08ce53-8040-4043-a96a-55933807d7d8"
version: "2.3.0.0"
targetAbi: "10.11.5.0"
framework: "net9.0"
overview: "This plugin allows for the exclusion of files based on the specifications outlined in the `.jellyfinignore` file."
description: >
  This plugin allows for the exclusion of files based on the specifications outlined in the `.jellyfinignore` file.
category: "General"
owner: "arition"
artifacts:
  - "Jellyfin.Plugin.Ignore.dll"
  - "Ignore.dll"
changelog: >
  2026-01-01 Update Jellyfin SDK to 10.11.5 and .NET 9.0
  2025-05-26 Update Jellyfin SDK to 10.10.7
  2024-07-08 Update Jellyfin SDK to 10.9
  2023-04-10 Update description
  2022-08-22 Init
